Add improvements for default permission handling
entgra/device-mgt-core pull request #5
Opened 2024-12-05 17:41 UTC by NKavindya

## Purpose
> Fixes related to: https://roadmap.entgra.net/issues/12195

## Approach
> I updated the updateScopeMetadataEntryWithDefaultScopes method by making it parameterized and reusable to handle both metadata entry updates and registry permission additions.

> To achieve this, I refactored the method to accept parameters for different permission sources, enabling it to handle lifecycle-state-related permissions and other default scopes dynamically. The default scopes, previously added through scattered sources, are now consolidated and fetched directly from the cdm configuration. For lifecycle-state-related permissions, I updated the application-mgt XML parsing logic to use the same reusable method, ensuring consistency.

> Additionally, I cleaned up redundant code by removing older implementations for default scope addition. The updated logic now centralizes default permission handling, improving maintainability. These changes make the permission management flow easier to extend in the future.

2024-12-15 02:45 UTC, lasanthaDLPDS requested changes

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/apimgt-extensions/io.entgra.device.mgt.core.apimgt.application.extension.api/src/main/webapp/META-INF/permissions.xml
>  <PermissionConfiguration>
Can't we delete the whole file?

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/apimgt-extensions/io.entgra.device.mgt.core.apimgt.webapp.publisher/src/main/java/io/entgra/device/mgt/core/apimgt/webapp/publisher/APIPublisherServiceImpl.java
> +                        }
In the catch block, don't catch chain of exceptions from a single catch block.

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/apimgt-extensions/io.entgra.device.mgt.core.apimgt.webapp.publisher/src/main/java/io/entgra/device/mgt/core/apimgt/webapp/publisher/APIPublisherStartupHandler.java
> +                DeviceManagementConfig deviceManagementConfig = DeviceConfigurationManager.getInstance().getDeviceManagementConfig();
Do we need to load the "DeviceManagementConfig" twice in this method?

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/apimgt-extensions/io.entgra.device.mgt.core.apimgt.webapp.publisher/src/main/java/io/entgra/device/mgt/core/apimgt/webapp/publisher/APIPublisherStartupHandler.java
> +            log.error(msg, e);
If you are not throwing an error, what's the point of having a String object here? There is no point of having a object, just log the message.

            log.error("Error when adding default permission to the registry ",  e);

Further, in the "MetadataManagementException" log the exception also.

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/application-mgt/io.entgra.device.mgt.core.application.mgt.common/pom.xml
> +                            io.entgra.device.mgt.core.device.mgt.core.config.*,
Add the version.

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/application-mgt/io.entgra.device.mgt.core.application.mgt.core/pom.xml
> +                            io.entgra.device.mgt.core.apimgt.webapp.publisher.exception*,
Add the version

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/application-mgt/io.entgra.device.mgt.core.application.mgt.core/pom.xml
> +            <version>3.12.0</version>
Don't specify the version number in pom files of sub-modules.

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/application-mgt/io.entgra.device.mgt.core.application.mgt.core/pom.xml
> +            <artifactId>io.entgra.device.mgt.core.apimgt.webapp.publisher</artifactId>
Add the "provided" scope

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/application-mgt/io.entgra.device.mgt.core.application.mgt.core/pom.xml
> +            <scope>test</scope>
Whats the reason for having test scope here?

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/certificate-mgt/io.entgra.device.mgt.core.certificate.mgt.api/src/main/webapp/META-INF/permissions.xml
> -    <APIVersion></APIVersion>
We can delete the whole file right?

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/certificate-mgt/io.entgra.device.mgt.core.certificate.mgt.cert.admin.api/src/main/webapp/META-INF/permissions.xml
> -    <APIVersion></APIVersion>
We can delete the whole file, right?

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/device-mgt/io.entgra.device.mgt.core.device.mgt.core/src/main/java/io/entgra/device/mgt/core/device/mgt/core/authorization/DeviceAccessAuthorizationServiceImpl.java
> -        permission.setName(CDM_ADMIN);
Do we need to keep "CDM_ADMIN" constant.

2024-12-15 02:45 UTC, lasanthaDLPDS commented on components/device-mgt/io.entgra.device.mgt.core.device.mgt.core/src/main/java/io/entgra/device/mgt/core/device/mgt/core/authorization/GroupAccessAuthorizationServiceImpl.java
> -        permission.setName(GROUP_ADMIN);
Do we need to keep "GROUP_ADMIN" constant?

2024-12-16 01:34 UTC, R4JxF60 commented on components/apimgt-extensions/io.entgra.device.mgt.core.apimgt.webapp.publisher/pom.xml
> +                            io.entgra.device.mgt.core.device.mgt.core.permission.mgt.*;version="${io.entgra.device.mgt.core.version.range}",
Imports the required package, no need to import all the packages which match the wildcard.

2024-12-16 01:36 UTC, R4JxF60 commented on components/application-mgt/io.entgra.device.mgt.core.application.mgt.common/pom.xml
> +                            io.entgra.device.mgt.core.device.mgt.core.config.*,
Import the required packages, remove the wildcards.

2024-12-20 12:08 UTC, merged